version: "2"

services:
  app:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_OPTS
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - "8080:8080"

  storage:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg8675309
      - POSTGRES_DB=springbootdb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
