version: "2"

services:
  app:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_OPTS
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_SERVICE_HOST
      - POSTGRES_SERVICE_PORT
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ports:
      - "80:8080"

  storage:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes_from:
      - storageData
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"

  storageData:
    image: postgres:9.5-alpine
    entrypoint: /bin/bash
